#!/bin/bash

# Make sure permissions are correct for the serverpod directory
chown -R ec2-user:ec2-user /home/ec2-user/serverpod

# Set correct permissions for start script
chmod 755 /home/ec2-user/serverpod/upload/dart_desk_be_server/deploy/aws/scripts/run_serverpod
chmod 755 /home/ec2-user/serverpod/upload/dart_desk_be_server/bin/server

# Stop the server if it's running, copy files, and restart
systemctl stop serverpod

rm -rf /home/ec2-user/serverpod/active/
cp -rp /home/ec2-user/serverpod/upload/ /home/ec2-user/serverpod/active/

systemctl start serverpod
