services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dart_desk_be
      POSTGRES_PASSWORD: "eV6EEUn3k8unm21DdBvjjYKfRT26ykHV"
    volumes:
      - dart_desk_be_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "XC3omJ0iAOoMHjC9H_BjIH3bI0XNrzjx"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dart_desk_be_test
      POSTGRES_PASSWORD: "NQIVOtKWq-tjftjLzXoQ13rysmlJgDSg"
    volumes:
      - dart_desk_be_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "SHTat41HepfaW0MxRQMTLyjoGyLYlcJh"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  dart_desk_be_data:
  dart_desk_be_test_data:
