name: flutter_cms_be_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 2.9.2
  serverpod_auth_client: 2.9.2
  serverpod_auth_google_flutter: 2.9.2
  serverpod_auth_shared_flutter: 2.9.2

  flutter:
    sdk: flutter
  flutter_cms:
    path: ../../flutter_cms/packages/flutter_cms
  shadcn_ui: ^0.39.14
